server:
  port: 8082

# Database configuration
spring:
  datasource:
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

# Application configuration
app:
  jwt:
    expiration: 86400000 # In Milliseconds
    secret: "01d179b40f130473197341d1cd7e6299"
